name: Refresh Data

on:
  workflow_dispatch:
  schedule:
    - cron: '15 9 * * *'

jobs:
  refresh:
    name: Refresh snapshots
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      PNPM_HOME: ~/.local/share/pnpm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Seed data if empty
        run: pnpm run seed
      - name: Refresh all adapters
        run: pnpm run refresh:all
      - name: Validate data
        run: pnpm run validate
      - name: Linkcheck (best effort)
        run: pnpm run linkcheck
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git commit -am "chore: refresh data"
          fi
      - name: Create PR
        if: ${{ github.event_name == 'schedule' }}
        uses: peter-evans/create-pull-request@v5
        with:
          branch: chore/refresh-${{ github.run_id }}
          title: 'chore: automated data refresh'
          body: 'Daily refresh generated by CI.'
          delete-branch: true
