name = "bsi-devmode-worker"
main = "src/index.ts"
compatibility_date = "2024-09-01"

[[kv_namespaces]]
binding = "FLAGS"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[vars]
UE_UPSTREAM = "https://ue-frontend.internal"
